// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApwqHXtKjB29TVadYYpdCWe-jzGW4qD4E',
    appId: '1:602442336270:web:d5bf58307f47779d2ed45f',
    messagingSenderId: '602442336270',
    projectId: 'my-reddit-fd454',
    authDomain: 'my-reddit-fd454.firebaseapp.com',
    storageBucket: 'my-reddit-fd454.appspot.com',
    measurementId: 'G-64PTD53DBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnetX92mdsF8WYQawRPNsbZpmBJpQdFhc',
    appId: '1:602442336270:android:0f724db0d1d91d642ed45f',
    messagingSenderId: '602442336270',
    projectId: 'my-reddit-fd454',
    storageBucket: 'my-reddit-fd454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQsQj_GgNazwqbZDYrDLDXBDp0g1sH4y4',
    appId: '1:602442336270:ios:3be068ddd89d51c22ed45f',
    messagingSenderId: '602442336270',
    projectId: 'my-reddit-fd454',
    storageBucket: 'my-reddit-fd454.appspot.com',
    iosClientId: '602442336270-27i3fucuflviicqboum4r8uat5cn878l.apps.googleusercontent.com',
    iosBundleId: 'com.example.myReddit',
  );
}
